language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest test/ -v
  - pycodestyle *.py
after_script:
  - py.test --cov=.
notification:
  email: false
